version: '3.8'

services:
  app:
    build:
      context: .  # 프로젝트 루트 디렉토리를 빌드 컨텍스트로 사용
      dockerfile: Dockerfile  # Dockerfile이 루트에 있음
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - redis
      - h2

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  h2:
    image: oscarfonts/h2
    container_name: h2
    environment:
      - H2_OPTIONS=-tcp -tcpAllowOthers -ifNotExists
      - H2_TCP_PORT=1521
    ports:
      - "1521:1521"
    volumes:
      - ./h2/:/opt/h2-data
    restart: always